import { Place, Alert, ExchangeOffice, DressCode, PriceScanItem, Circuit, SafeRoute } from './types'

export const MARRAKECH_CENTER: [number, number] = [31.6295, -7.9811]

export const GUIDE_AVATARS = {
  welcome: '/avatars/guide-welcome.png',
  food: '/avatars/guide-food.png',
  shopping: '/avatars/guide-shopping.png',
  monuments: '/avatars/guide-monuments.png',
}

export const CATEGORIES = [
  { id: 'restaurant', label: 'Restaurants', labelAr: 'مطاعم', icon: 'UtensilsCrossed', avatar: 'food' },
  { id: 'hotel', label: 'Hotels', labelAr: 'فنادق', icon: 'Building2', avatar: 'welcome' },
  { id: 'riad', label: 'Riads', labelAr: 'رياض', icon: 'Home', avatar: 'welcome' },
  { id: 'monument', label: 'Monuments', labelAr: 'معالم', icon: 'Landmark', avatar: 'monuments' },
  { id: 'shopping', label: 'Shopping', labelAr: 'تسوق', icon: 'ShoppingBag', avatar: 'shopping' },
  { id: 'rooftop', label: 'Rooftops', labelAr: 'أسطح', icon: 'Sun', avatar: 'food' },
  { id: 'spa', label: 'Hammams & Spas', labelAr: 'حمامات', icon: 'Sparkles', avatar: 'welcome' },
  { id: 'garden', label: 'Gardens', labelAr: 'حدائق', icon: 'TreePalm', avatar: 'monuments' },
  { id: 'museum', label: 'Museums', labelAr: 'متاحف', icon: 'GalleryVertical', avatar: 'monuments' },
  { id: 'excursion', label: 'Excursions', labelAr: 'رحلات', icon: 'Mountain', avatar: 'welcome' },
] as const

export const INTERESTS = [
  'History & Culture',
  'Food & Cuisine',
  'Shopping & Souks',
  'Nature & Gardens',
  'Photography',
  'Adventure',
  'Relaxation',
  'Art & Crafts',
  'Architecture',
  'Nightlife',
  'Local Experiences',
  'Luxury',
]

export const DIETARY_RESTRICTIONS = [
  'Vegetarian',
  'Vegan',
  'Halal',
  'Kosher',
  'Gluten-Free',
  'Dairy-Free',
  'Nut-Free',
  'Shellfish Allergy',
  'No Pork',
]

export const LANGUAGES = [
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'ar', label: 'العربية', flag: '🇲🇦' },
  { code: 'es', label: 'Español', flag: '🇪🇸' },
  { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
]

export const SAMPLE_PLACES: Place[] = [
  {
    id: '1',
    name: 'Jardin Majorelle',
    nameAr: 'حديقة ماجوريل',
    category: 'garden',
    description: 'A stunning two-acre botanical garden featuring vibrant cobalt blue buildings, exotic plants from five continents, and the Berber Museum.',
    ecoDescription: 'An eco-certified location supporting local biodiversity and sustainable practices.',
    address: 'Rue Yves Saint Laurent, Marrakech',
    coordinates: [31.6417, -8.0035],
    rating: 4.7,
    reviews: 12453,
    priceRange: 2,
    priceMAD: { min: 70, max: 150 },
    openingHours: '8:00 AM - 6:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800',
    tags: ['garden', 'museum', 'photography', 'peaceful'],
    isEcoCertified: true,
    isAccessible: true,
    hasShadedAreas: true,
    isFamilyFriendly: true,
  },
  {
    id: '2',
    name: 'Jemaa el-Fnaa',
    nameAr: 'ساحة جامع الفناء',
    category: 'monument',
    description: 'The heart of Marrakech - a UNESCO World Heritage site filled with street performers, food stalls, and traditional storytellers.',
    address: 'Place Jemaa el-Fnaa, Medina',
    coordinates: [31.6258, -7.9891],
    rating: 4.5,
    reviews: 34521,
    priceRange: 1,
    priceMAD: { min: 0, max: 0 },
    openingHours: 'Open 24 hours',
    imageUrl: 'https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=800',
    tags: ['cultural', 'food', 'entertainment', 'nightlife'],
    isAccessible: false,
    hasShadedAreas: false,
    isFamilyFriendly: true,
  },
  {
    id: '3',
    name: 'Bahia Palace',
    nameAr: 'قصر الباهية',
    category: 'monument',
    description: 'A 19th-century palace showcasing the finest Moroccan and Islamic architecture with stunning gardens and zellige tilework.',
    address: 'Avenue Imam El Ghazali, Medina',
    coordinates: [31.6214, -7.9831],
    rating: 4.6,
    reviews: 8932,
    priceRange: 1,
    priceMAD: { min: 70, max: 70 },
    openingHours: '9:00 AM - 5:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=800',
    tags: ['history', 'architecture', 'photography', 'culture'],
    isAccessible: true,
    hasShadedAreas: true,
    isFamilyFriendly: true,
  },
  {
    id: '4',
    name: 'Le Jardin Secret',
    nameAr: 'الحديقة السرية',
    category: 'garden',
    description: 'A hidden oasis in the heart of the Medina featuring Islamic and exotic gardens with a stunning tower offering panoramic views.',
    ecoDescription: 'Uses traditional irrigation systems and promotes water conservation.',
    address: '121 Rue Mouassine, Medina',
    coordinates: [31.6312, -7.9892],
    rating: 4.4,
    reviews: 5621,
    priceRange: 2,
    priceMAD: { min: 60, max: 90 },
    openingHours: '9:30 AM - 7:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800',
    tags: ['garden', 'peaceful', 'photography', 'shade'],
    isEcoCertified: true,
    isAccessible: false,
    hasShadedAreas: true,
    isFamilyFriendly: true,
  },
  {
    id: '5',
    name: 'Café Nomad',
    nameAr: 'مقهى نوماد',
    category: 'rooftop',
    description: 'A trendy rooftop restaurant with panoramic views over the spice souk, serving modern Moroccan cuisine.',
    address: '1 Derb Aarjan, Medina',
    coordinates: [31.6283, -7.9867],
    rating: 4.3,
    reviews: 3421,
    priceRange: 2,
    priceMAD: { min: 100, max: 300 },
    openingHours: '10:00 AM - 11:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
    tags: ['food', 'rooftop', 'views', 'modern'],
    isAccessible: false,
    hasShadedAreas: true,
    isFamilyFriendly: true,
  },
  {
    id: '6',
    name: 'Souk Semmarine',
    nameAr: 'سوق السمارين',
    category: 'shopping',
    description: 'The main souk in Marrakech offering traditional crafts, textiles, leather goods, and spices.',
    ecoDescription: 'Supporting local artisans and traditional craftsmanship.',
    address: 'Souk Semmarine, Medina',
    coordinates: [31.6289, -7.9876],
    rating: 4.4,
    reviews: 15632,
    priceRange: 2,
    priceMAD: { min: 0, max: 5000 },
    openingHours: '9:00 AM - 8:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1531501410720-c8d437636169?w=800',
    tags: ['shopping', 'crafts', 'traditional', 'souvenirs'],
    isAccessible: false,
    hasShadedAreas: true,
    isFamilyFriendly: true,
  },
  {
    id: '7',
    name: 'Riad Yasmine',
    nameAr: 'رياض ياسمين',
    category: 'riad',
    description: 'A boutique riad famous for its stunning Instagram-worthy pool and traditional Moroccan architecture.',
    address: 'Derb El Hammam, Medina',
    coordinates: [31.6298, -7.9845],
    rating: 4.8,
    reviews: 2341,
    priceRange: 3,
    priceMAD: { min: 1200, max: 3000 },
    imageUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
    tags: ['accommodation', 'pool', 'instagram', 'luxury'],
    isAccessible: false,
    hasShadedAreas: true,
    isFamilyFriendly: true,
  },
  {
    id: '8',
    name: 'Koutoubia Mosque',
    nameAr: 'جامع الكتبية',
    category: 'monument',
    description: 'The largest mosque in Marrakech with its iconic 77-meter minaret visible from miles away. Gardens open to all.',
    address: 'Avenue Mohammed V, Medina',
    coordinates: [31.6237, -7.9934],
    rating: 4.7,
    reviews: 9876,
    priceRange: 1,
    priceMAD: { min: 0, max: 0 },
    openingHours: 'Gardens: 8:00 AM - 6:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?w=800',
    tags: ['mosque', 'architecture', 'landmark', 'gardens'],
    isAccessible: true,
    hasShadedAreas: true,
    isFamilyFriendly: true,
  },
  {
    id: '9',
    name: 'Hammam de la Rose',
    nameAr: 'حمام الورد',
    category: 'spa',
    description: 'A luxurious traditional hammam experience with organic products and professional treatments.',
    address: '130 Dar El Bacha, Medina',
    coordinates: [31.6334, -7.9901],
    rating: 4.6,
    reviews: 1234,
    priceRange: 3,
    priceMAD: { min: 400, max: 1500 },
    openingHours: '9:00 AM - 8:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800',
    tags: ['spa', 'relaxation', 'traditional', 'wellness'],
    isAccessible: true,
    hasShadedAreas: true,
    isFamilyFriendly: false,
  },
  {
    id: '10',
    name: 'La Mamounia',
    nameAr: 'المامونية',
    category: 'hotel',
    description: 'One of the most famous hotels in the world, featuring stunning gardens, luxurious accommodations, and world-class dining.',
    address: 'Avenue Bab Jdid, Medina',
    coordinates: [31.6198, -7.9956],
    rating: 4.9,
    reviews: 4567,
    priceRange: 4,
    priceMAD: { min: 5000, max: 50000 },
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
    tags: ['luxury', 'hotel', 'garden', 'dining'],
    isAccessible: true,
    hasShadedAreas: true,
    isFamilyFriendly: true,
  },
]

export const SAMPLE_ALERTS: Alert[] = [
  {
    id: '1',
    type: 'weather',
    title: 'High Temperature Alert',
    message: 'Temperature expected to reach 42°C today. Stay hydrated and seek shade during 12-4 PM.',
    severity: 'warning',
    relevantTo: ['sun-sensitive'],
  },
  {
    id: '2',
    type: 'scam',
    title: 'Beware of "Closed Road" Scam',
    message: 'If someone tells you a road is closed and offers to guide you, politely decline. Roads in the Medina are rarely closed.',
    severity: 'info',
  },
  {
    id: '3',
    type: 'tip',
    title: 'Negotiation Tip',
    message: 'Start at 50% of the asking price when shopping in souks. It is expected and part of the culture!',
    severity: 'info',
  },
  {
    id: '4',
    type: 'health',
    title: 'Nut Allergy Warning',
    message: 'Many Moroccan dishes contain almonds and other nuts. Always ask "Bla louz?" (without almonds) when ordering.',
    severity: 'warning',
    relevantTo: ['allergic-nuts'],
  },
]

export const PRICE_REFERENCES = {
  'Fresh orange juice': { min: 5, max: 10, unit: 'glass' },
  'Petit taxi (city)': { min: 20, max: 50, unit: 'trip' },
  'Traditional tagine': { min: 50, max: 150, unit: 'dish' },
  'Mint tea': { min: 10, max: 25, unit: 'pot' },
  'Henna (basic)': { min: 50, max: 150, unit: 'design' },
  'Leather bag': { min: 150, max: 500, unit: 'item' },
  'Argan oil (100ml)': { min: 80, max: 200, unit: 'bottle' },
  'Museum entry': { min: 50, max: 100, unit: 'person' },
}

export const EMERGENCY_CONTACTS = {
  'Tourist Police': '19',
  'Emergency': '15',
  'Fire': '150',
  'Ambulance': '150',
  'French Consulate': '+212 5 24 38 82 00',
  'US Consulate': '+212 5 22 26 45 50',
}

export const CURRENCY_SYMBOLS: Record<string, string> = {
  MAD: 'د.م.',
  USD: '$',
  EUR: '€',
  GBP: '£',
  CAD: 'C$',
  AUD: 'A$',
}

export const EXCHANGE_RATES: Record<string, number> = {
  MAD: 1,
  USD: 0.099,
  EUR: 0.091,
  GBP: 0.078,
  CAD: 0.134,
  AUD: 0.152,
}

// MEDICAL CONDITIONS for health tracking
export const MEDICAL_CONDITIONS = [
  'Diabetes',
  'Heart Condition',
  'Asthma',
  'High Blood Pressure',
  'Epilepsy',
  'Pregnancy',
  'Arthritis',
  'Back Problems',
  'Anxiety/Panic Disorder',
  'Vertigo',
  'Heat Intolerance',
  'Other',
]

// TRUSTED EXCHANGE OFFICES
export const EXCHANGE_OFFICES: ExchangeOffice[] = [
  {
    id: 'ex1',
    name: 'Bureau de Change Jemaa el-Fnaa',
    address: 'Near Cafe de France, Jemaa el-Fnaa',
    coordinates: [31.6261, -7.9893],
    rating: 4.5,
    isTrusted: true,
    fees: 'low',
    openingHours: '8:00 AM - 9:00 PM',
    phone: '+212 5 24 44 12 34',
    tips: 'One of the most reliable exchanges in the Medina. Always count your money before leaving.',
  },
  {
    id: 'ex2',
    name: 'Attijariwafa Bank - Gueliz',
    address: 'Avenue Mohammed V, Gueliz',
    coordinates: [31.6343, -8.0089],
    rating: 4.8,
    isTrusted: true,
    fees: 'low',
    openingHours: '8:30 AM - 4:30 PM (Mon-Fri)',
    phone: '+212 5 24 43 56 78',
    tips: 'Official bank with best rates. Bring your passport.',
  },
  {
    id: 'ex3',
    name: 'BMCE Bank - Medina',
    address: 'Rue Bab Agnaou, Medina',
    coordinates: [31.6218, -7.9912],
    rating: 4.6,
    isTrusted: true,
    fees: 'low',
    openingHours: '8:30 AM - 4:00 PM (Mon-Fri)',
    tips: 'Reliable bank exchange. ATM available 24/7.',
  },
  {
    id: 'ex4',
    name: 'Currency Exchange Koutoubia',
    address: 'Near Koutoubia Mosque, Avenue Mohammed V',
    coordinates: [31.6241, -7.9936],
    rating: 4.2,
    isTrusted: true,
    fees: 'medium',
    openingHours: '9:00 AM - 8:00 PM',
    tips: 'Convenient location but slightly higher fees than banks.',
  },
]

// DRESS CODE RECOMMENDATIONS
export const DRESS_CODES: DressCode[] = [
  {
    placeType: 'mosque',
    required: ['Long pants/skirt covering knees', 'Covered shoulders', 'Headscarf for women (provided at entrance)'],
    recommended: ['Loose-fitting clothes', 'Remove shoes at entrance'],
    avoid: ['Shorts', 'Tank tops', 'Tight clothing', 'Short skirts'],
    tips: 'Non-Muslims can only visit mosque gardens, not interior. Koutoubia gardens are open to all.',
  },
  {
    placeType: 'medina',
    required: ['Comfortable walking shoes'],
    recommended: ['Light, breathable fabrics', 'Hat or scarf for sun', 'Crossbody bag (not backpack)', 'Modest clothing'],
    avoid: ['Revealing clothing', 'Expensive jewelry', 'High heels'],
    tips: 'Dress modestly to avoid unwanted attention. Light colors reflect heat better.',
  },
  {
    placeType: 'hammam',
    required: ['Swimsuit or underwear', 'Flip-flops'],
    recommended: ['Bring your own towel', 'Hair tie', 'Change of underwear'],
    avoid: ['Jewelry', 'Makeup'],
    tips: 'Traditional hammams are gender-separated. Tourist hammams often provide everything.',
  },
  {
    placeType: 'luxury_restaurant',
    required: ['Smart casual attire'],
    recommended: ['Closed shoes', 'Collared shirt for men', 'Evening dress for upscale venues'],
    avoid: ['Flip-flops', 'Beachwear', 'Very casual sportswear'],
    tips: 'Rooftop restaurants and riads often have dress codes, especially in the evening.',
  },
  {
    placeType: 'souk',
    required: ['Comfortable shoes', 'Secure bag'],
    recommended: ['Pockets for small change', 'Light layers', 'Sunglasses'],
    avoid: ['Flashy jewelry', 'Open bags', 'Anything you cannot walk in'],
    tips: 'Keep valuables hidden. Wear clothes you do not mind getting dusty.',
  },
  {
    placeType: 'desert_excursion',
    required: ['Closed-toe shoes', 'Long pants', 'Sun protection'],
    recommended: ['Scarf/shemagh for dust', 'Layers for evening cold', 'Sunscreen SPF 50+'],
    avoid: ['Sandals', 'Dark colors that absorb heat'],
    tips: 'Desert temperatures can drop significantly at night. Bring a warm layer.',
  },
]

// PRICE SCANNER ITEMS - for bargaining help
export const PRICE_SCAN_ITEMS: PriceScanItem[] = [
  {
    id: 'ps1',
    name: 'Leather Bag (Medium)',
    nameAr: 'حقيبة جلدية',
    category: 'leather',
    priceRange: { min: 150, max: 600 },
    fairPrice: 250,
    tips: ['Check stitching quality', 'Smell should not be too strong (over-treated)', 'Start at 40% of asking price'],
    whereToFind: ['Souk Semmarine', 'Tanneries area'],
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400',
  },
  {
    id: 'ps9',
    name: 'Moroccan Tea Set',
    nameAr: 'طقم شاي مغربي',
    category: 'metalwork',
    priceRange: { min: 200, max: 800 },
    fairPrice: 350,
    tips: ['Check for silver plating quality', 'Ensure glasses are included', 'Brass is cheaper than silver-plated'],
    whereToFind: ['Souk des Ferblantiers', 'Souk Semmarine'],
    imageUrl: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400',
  },
  {
    id: 'ps10',
    name: 'Ceramic Plate (Hand-painted)',
    nameAr: 'صحن خزفي مرسوم يدويا',
    category: 'pottery',
    priceRange: { min: 80, max: 300 },
    fairPrice: 150,
    tips: ['Check for hand-painted vs stenciled', 'Fez ceramics are more valuable', 'Ask about food-safe glazes'],
    whereToFind: ['Pottery Souk', 'Ensemble Artisanal'],
    imageUrl: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400',
  },
  {
    id: 'ps11',
    name: 'Moroccan Pouf (Leather)',
    nameAr: 'بوف جلدي مغربي',
    category: 'leather',
    priceRange: { min: 300, max: 900 },
    fairPrice: 450,
    tips: ['Ask if it comes stuffed or empty', 'Check leather quality and stitching', 'Embroidered ones cost more'],
    whereToFind: ['Leather Souks', 'Tanneries'],
    imageUrl: 'https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=400',
  },
  {
    id: 'ps12',
    name: 'Thuya Wood Box',
    nameAr: 'صندوق خشب العرعر',
    category: 'woodwork',
    priceRange: { min: 100, max: 500 },
    fairPrice: 200,
    tips: ['Smell the wood - thuya has a distinctive scent', 'Check for solid wood vs veneer', 'Essaouira pieces are most authentic'],
    whereToFind: ['Woodworking Souk', 'Near Ben Youssef'],
    imageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=400',
  },
  {
    id: 'ps13',
    name: 'Kaftan (Traditional)',
    nameAr: 'قفطان تقليدي',
    category: 'textiles',
    priceRange: { min: 500, max: 3000 },
    fairPrice: 1000,
    tips: ['Check fabric quality and embroidery', 'Ask about tailor alterations', 'Silk costs more than polyester'],
    whereToFind: ['Textile Souks', 'Kissaria'],
    imageUrl: 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=400',
  },
  {
    id: 'ps14',
    name: 'Saffron (10g)',
    nameAr: 'زعفران',
    category: 'food',
    priceRange: { min: 50, max: 200 },
    fairPrice: 80,
    tips: ['Real saffron has a distinctive smell', 'Threads should be red with orange tips', 'Beware of dyed safflower'],
    whereToFind: ['Spice Souk', 'Rahba Kedima'],
    imageUrl: 'https://images.unsplash.com/photo-1599420186946-7b6fb4e297f0?w=400',
  },
  {
    id: 'ps15',
    name: 'Moroccan Lamp (Large)',
    nameAr: 'مصباح مغربي كبير',
    category: 'decor',
    priceRange: { min: 300, max: 1200 },
    fairPrice: 500,
    tips: ['Ask about wiring for your country', 'Glass panes are fragile - ask about shipping', 'Brass vs iron affects price'],
    whereToFind: ['Lamp Souk', 'Place des Ferblantiers'],
    imageUrl: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=400',
  },
  {
    id: 'ps2',
    name: 'Berber Carpet (Small, 1x1.5m)',
    nameAr: 'سجادة أمازيغية',
    category: 'carpet',
    priceRange: { min: 500, max: 3000 },
    fairPrice: 1200,
    tips: ['Check for hand-knotted vs machine-made', 'Natural dyes cost more', 'Ask for certificate of authenticity'],
    whereToFind: ['Carpet souks near Jemaa el-Fnaa', 'Ensemble Artisanal'],
  },
  {
    id: 'ps3',
    name: 'Argan Oil (100ml, Cosmetic)',
    nameAr: 'زيت أرگان',
    category: 'beauty',
    priceRange: { min: 80, max: 250 },
    fairPrice: 120,
    tips: ['Pure oil should be almost odorless', 'Check for cooperative certification', 'Culinary argan is different'],
    whereToFind: ['Cooperative shops', 'Pharmacies in Gueliz'],
  },
  {
    id: 'ps4',
    name: 'Moroccan Lantern (Metal, Medium)',
    nameAr: 'فانوس مغربي',
    category: 'decor',
    priceRange: { min: 100, max: 500 },
    fairPrice: 200,
    tips: ['Check for sharp edges', 'Brass costs more than iron', 'Ask about shipping options'],
    whereToFind: ['Lamp souk near Place des Ferblantiers'],
  },
  {
    id: 'ps5',
    name: 'Tagine Pot (Decorative)',
    nameAr: 'طاجين',
    category: 'pottery',
    priceRange: { min: 50, max: 200 },
    fairPrice: 80,
    tips: ['Decorative vs cooking tagines are different', 'Cooking ones need seasoning', 'Check for cracks'],
    whereToFind: ['Pottery souks', 'Ensemble Artisanal'],
  },
  {
    id: 'ps6',
    name: 'Babouche Slippers',
    nameAr: 'بلغة',
    category: 'leather',
    priceRange: { min: 50, max: 200 },
    fairPrice: 80,
    tips: ['Real leather molds to your foot', 'Check stitching', 'Buy slightly tight - they stretch'],
    whereToFind: ['Souk Smata (slipper souk)'],
  },
  {
    id: 'ps7',
    name: 'Spice Mix (Ras el Hanout, 100g)',
    nameAr: 'راس الحانوت',
    category: 'food',
    priceRange: { min: 20, max: 80 },
    fairPrice: 40,
    tips: ['Smell before buying', 'Pre-packaged is often fresher', 'Ask for recipes'],
    whereToFind: ['Spice souk', 'Rahba Kedima square'],
  },
  {
    id: 'ps8',
    name: 'Silver Jewelry (Berber Ring)',
    nameAr: 'خاتم فضي أمازيغي',
    category: 'jewelry',
    priceRange: { min: 100, max: 500 },
    fairPrice: 200,
    tips: ['Check for 925 stamp', 'Real silver does not discolor quickly', 'Antique pieces cost more'],
    whereToFind: ['Jewish quarter (Mellah)', 'Jewelry souks'],
  },
]

// PRE-MADE CIRCUITS
export const CIRCUITS: Circuit[] = [
  {
    id: 'c1',
    name: 'Historic Medina Walk',
    nameAr: 'جولة المدينة التاريخية',
    description: 'Discover the heart of Marrakech through its most iconic monuments and hidden gems.',
    duration: '4-5 hours',
    difficulty: 'moderate',
    type: 'cultural',
    highlights: ['Bahia Palace', 'Saadian Tombs', 'Koutoubia Mosque', 'Ben Youssef Madrasa'],
    places: ['3', '8', '2'],
    bestTime: 'Morning (8-12 AM) to avoid heat',
    dressCode: ['Modest clothing', 'Comfortable walking shoes', 'Hat/sunscreen'],
    budget: { min: 200, max: 400 },
    imageUrl: 'https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=800',
  },
  {
    id: 'c2',
    name: 'Food Lover Paradise',
    nameAr: 'جنة عشاق الطعام',
    description: 'A culinary journey through the best street food, traditional restaurants, and hidden gems.',
    duration: '3-4 hours',
    difficulty: 'easy',
    type: 'food',
    highlights: ['Street food tasting', 'Traditional tagine', 'Mint tea ceremony', 'Local bakeries'],
    places: ['5', '2'],
    bestTime: 'Evening (5-9 PM) when food stalls open',
    dressCode: ['Casual comfortable', 'Bring wet wipes'],
    budget: { min: 150, max: 350 },
    imageUrl: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?w=800',
  },
  {
    id: 'c3',
    name: 'Souk Shopping Adventure',
    nameAr: 'مغامرة التسوق في السوق',
    description: 'Navigate the labyrinthine souks like a local and find the best deals on authentic crafts.',
    duration: '3-4 hours',
    difficulty: 'moderate',
    type: 'shopping',
    highlights: ['Leather goods', 'Spices', 'Carpets', 'Lanterns', 'Bargaining tips'],
    places: ['6'],
    bestTime: 'Morning (10 AM - 1 PM) when shops are fully open',
    dressCode: ['Secure crossbody bag', 'Comfortable shoes', 'Modest clothing'],
    budget: { min: 300, max: 2000 },
    imageUrl: 'https://images.unsplash.com/photo-1531501410720-c8d437636169?w=800',
  },
  {
    id: 'c4',
    name: 'Zen Garden Escape',
    nameAr: 'ملاذ الحدائق الهادئة',
    description: 'Escape the bustling medina with a peaceful tour of Marrakech\'s most beautiful gardens.',
    duration: '4-5 hours',
    difficulty: 'easy',
    type: 'nature',
    highlights: ['Jardin Majorelle', 'Le Jardin Secret', 'Menara Gardens', 'Cyber Park'],
    places: ['1', '4'],
    bestTime: 'Morning or late afternoon to avoid midday heat',
    dressCode: ['Sun protection', 'Light comfortable clothes', 'Water bottle'],
    budget: { min: 200, max: 350 },
    imageUrl: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800',
  },
  {
    id: 'c5',
    name: 'Romantic Riad Evening',
    nameAr: 'أمسية رومانسية في رياض',
    description: 'A magical evening for couples featuring rooftop dining and traditional entertainment.',
    duration: '4-5 hours',
    difficulty: 'easy',
    type: 'romantic',
    highlights: ['Sunset rooftop drinks', 'Traditional dinner', 'Live Gnaoua music', 'Starlit terrace'],
    places: ['5', '7', '10'],
    bestTime: 'Evening (6 PM onwards)',
    dressCode: ['Smart casual', 'Light jacket for evening'],
    budget: { min: 500, max: 1500 },
    imageUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
  },
  {
    id: 'c6',
    name: 'Family Fun Day',
    nameAr: 'يوم عائلي ممتع',
    description: 'A family-friendly itinerary with activities suitable for all ages.',
    duration: 'Full day',
    difficulty: 'easy',
    type: 'family',
    highlights: ['Garden exploration', 'Camel ride', 'Ice cream stop', 'Storytellers at Jemaa'],
    places: ['1', '2', '4'],
    bestTime: 'Start early morning, take midday break, return evening',
    dressCode: ['Comfortable for kids', 'Sun protection', 'Snacks and water'],
    budget: { min: 400, max: 800 },
    imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800',
  },
  {
    id: 'c7',
    name: 'Instagram Perfect Tour',
    nameAr: 'جولة الصور المثالية',
    description: 'Hit all the most photogenic spots in Marrakech for stunning social media content.',
    duration: '5-6 hours',
    difficulty: 'moderate',
    type: 'photo',
    highlights: ['Blue Majorelle walls', 'Colorful souks', 'Ornate doorways', 'Rooftop views'],
    places: ['1', '7', '5', '3'],
    bestTime: 'Golden hour (7-9 AM or 5-7 PM) for best light',
    dressCode: ['Photogenic outfits', 'Comfortable walking shoes'],
    budget: { min: 250, max: 450 },
    imageUrl: 'https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=800',
  },
]

// SAFE ROUTES with different preferences
export const SAFE_ROUTES: SafeRoute[] = [
  {
    id: 'sr1',
    name: 'Main Tourist Route',
    type: 'safest',
    description: 'Well-lit main streets with tourist police presence. From Jemaa el-Fnaa to Koutoubia Mosque.',
    waypoints: [[31.6258, -7.9891], [31.6245, -7.9912], [31.6237, -7.9934]],
    crowdLevel: 'high',
    safetyRating: 5,
    shadedPercentage: 30,
    estimatedTime: 15,
    features: ['Tourist police', 'Well-lit', 'Shops open', 'Many tourists'],
    startPoint: { name: 'Jemaa el-Fnaa', coordinates: [31.6258, -7.9891] as [number, number] },
    endPoint: { name: 'Koutoubia Mosque', coordinates: [31.6237, -7.9934] as [number, number] },
  },
  {
    id: 'sr2',
    name: 'Zen Passage',
    type: 'zen',
    description: 'Quiet derbs (alleys) away from the crowds, through residential areas. Perfect for a peaceful walk.',
    waypoints: [[31.6295, -7.9811], [31.6305, -7.9840], [31.6312, -7.9850], [31.6320, -7.9870], [31.6310, -7.9892]],
    crowdLevel: 'low',
    safetyRating: 4,
    shadedPercentage: 70,
    estimatedTime: 20,
    features: ['Quiet', 'Local life', 'Shaded alleys', 'Less crowded'],
    startPoint: { name: 'Mouassine Fountain', coordinates: [31.6295, -7.9811] as [number, number] },
    endPoint: { name: 'Dar El Bacha', coordinates: [31.6310, -7.9892] as [number, number] },
  },
  {
    id: 'sr3',
    name: 'Scent Trail',
    type: 'senteurs',
    description: 'Pass by herbalists, spice merchants, and orange blossom sellers through the aromatic souks.',
    waypoints: [[31.6289, -7.9876], [31.6285, -7.9868], [31.6283, -7.9860], [31.6280, -7.9855], [31.6278, -7.9850]],
    crowdLevel: 'medium',
    safetyRating: 4,
    shadedPercentage: 60,
    estimatedTime: 25,
    features: ['Aromatic', 'Herbal shops', 'Spice souk', 'Cultural'],
    startPoint: { name: 'Spice Square (Rahba Kedima)', coordinates: [31.6289, -7.9876] as [number, number] },
    endPoint: { name: 'Souk des Teinturiers', coordinates: [31.6278, -7.9850] as [number, number] },
  },
  {
    id: 'sr4',
    name: 'Scenic Walk',
    type: 'scenic',
    description: 'Beautiful architecture and photo opportunities along the way through historic riads.',
    waypoints: [[31.6298, -7.9845], [31.6285, -7.9838], [31.6270, -7.9832], [31.6250, -7.9830], [31.6214, -7.9831]],
    crowdLevel: 'medium',
    safetyRating: 4,
    shadedPercentage: 50,
    estimatedTime: 30,
    features: ['Photo spots', 'Architecture', 'Riads', 'Fountains'],
    startPoint: { name: 'Riad Yasmine Area', coordinates: [31.6298, -7.9845] as [number, number] },
    endPoint: { name: 'Bahia Palace', coordinates: [31.6214, -7.9831] as [number, number] },
  },
  {
    id: 'sr5',
    name: 'Garden Route',
    type: 'scenic',
    description: 'A peaceful route connecting the major gardens of Marrakech with plenty of shade.',
    waypoints: [[31.6417, -8.0035], [31.6380, -8.0010], [31.6350, -7.9980], [31.6312, -7.9892]],
    crowdLevel: 'low',
    safetyRating: 5,
    shadedPercentage: 80,
    estimatedTime: 45,
    features: ['Gardens', 'Shade', 'Nature', 'Peaceful'],
    startPoint: { name: 'Jardin Majorelle', coordinates: [31.6417, -8.0035] as [number, number] },
    endPoint: { name: 'Le Jardin Secret', coordinates: [31.6312, -7.9892] as [number, number] },
  },
  {
    id: 'sr6',
    name: 'Artisan Discovery',
    type: 'safest',
    description: 'Discover traditional craftsmen at work - leatherworkers, metalworkers, and woodcarvers.',
    waypoints: [[31.6356, -7.9788], [31.6340, -7.9810], [31.6320, -7.9840], [31.6315, -7.9865]],
    crowdLevel: 'medium',
    safetyRating: 4,
    shadedPercentage: 40,
    estimatedTime: 35,
    features: ['Craftsmen', 'Workshops', 'Authentic', 'Cultural'],
    startPoint: { name: 'Tanneries', coordinates: [31.6356, -7.9788] as [number, number] },
    endPoint: { name: 'Ben Youssef Madrasa', coordinates: [31.6315, -7.9865] as [number, number] },
  },
]

// MORE SAMPLE PLACES
export const MORE_PLACES: Place[] = [
  {
    id: '11',
    name: 'Saadian Tombs',
    nameAr: 'مقابر السعديين',
    category: 'monument',
    description: 'Stunning 16th-century royal necropolis with intricate carved cedar wood and stucco.',
    address: 'Rue de la Kasbah, Medina',
    coordinates: [31.6175, -7.9887],
    rating: 4.5,
    reviews: 7821,
    priceRange: 1,
    priceMAD: { min: 70, max: 70 },
    openingHours: '9:00 AM - 5:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800',
    tags: ['history', 'architecture', 'tombs', 'photography'],
    isAccessible: false,
    hasShadedAreas: true,
    isFamilyFriendly: true,
  },
  {
    id: '12',
    name: 'Ben Youssef Madrasa',
    nameAr: 'مدرسة ابن يوسف',
    category: 'monument',
    description: 'Former Islamic college with breathtaking zellige tilework and carved stucco.',
    address: 'Kaat Benahid, Medina',
    coordinates: [31.6315, -7.9865],
    rating: 4.7,
    reviews: 6543,
    priceRange: 1,
    priceMAD: { min: 50, max: 50 },
    openingHours: '9:00 AM - 6:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1548017537-e6e3a6f5fc06?w=800',
    tags: ['history', 'architecture', 'islamic', 'photography'],
    isAccessible: false,
    hasShadedAreas: true,
    isFamilyFriendly: true,
  },
  {
    id: '13',
    name: 'Menara Gardens',
    nameAr: 'حدائق المنارة',
    category: 'garden',
    description: 'Peaceful olive grove with a iconic pavilion and reflecting pool, Atlas Mountain views.',
    ecoDescription: 'Historic irrigation system still in use, supporting local agriculture.',
    address: 'Avenue de la Menara',
    coordinates: [31.6142, -8.0225],
    rating: 4.2,
    reviews: 5432,
    priceRange: 1,
    priceMAD: { min: 0, max: 0 },
    openingHours: '8:00 AM - 5:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1553522991-71439aa62779?w=800',
    tags: ['garden', 'peaceful', 'views', 'free'],
    isEcoCertified: true,
    isAccessible: true,
    hasShadedAreas: true,
    isFamilyFriendly: true,
  },
  {
    id: '14',
    name: 'Dar Si Said Museum',
    nameAr: 'متحف دار السي سعيد',
    category: 'museum',
    description: 'Beautiful 19th-century palace housing Moroccan arts and crafts collection.',
    address: 'Derb Si Said, Medina',
    coordinates: [31.6221, -7.9819],
    rating: 4.4,
    reviews: 2341,
    priceRange: 1,
    priceMAD: { min: 30, max: 30 },
    openingHours: '9:00 AM - 5:00 PM (Closed Tuesdays)',
    imageUrl: 'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=800',
    tags: ['museum', 'art', 'crafts', 'culture'],
    isAccessible: false,
    hasShadedAreas: true,
    isFamilyFriendly: true,
  },
  {
    id: '15',
    name: 'Le Foundouk',
    nameAr: 'الفندق',
    category: 'restaurant',
    description: 'Elegant restaurant in a restored caravanserai with modern Moroccan cuisine.',
    address: '55 Souk Hal Fassi, Medina',
    coordinates: [31.6301, -7.9862],
    rating: 4.5,
    reviews: 1876,
    priceRange: 3,
    priceMAD: { min: 200, max: 500 },
    openingHours: '12:00 PM - 3:00 PM, 7:00 PM - 11:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    tags: ['fine-dining', 'moroccan', 'romantic', 'rooftop'],
    isAccessible: false,
    hasShadedAreas: true,
    isFamilyFriendly: false,
  },
  {
    id: '16',
    name: 'Amal Center',
    nameAr: 'مركز أمل',
    category: 'restaurant',
    description: 'Non-profit training restaurant empowering disadvantaged women. Delicious home-style cooking.',
    ecoDescription: 'Social enterprise supporting local women and sustainable practices.',
    address: 'Rue Allal Ben Ahmed, Gueliz',
    coordinates: [31.6365, -8.0021],
    rating: 4.6,
    reviews: 3421,
    priceRange: 1,
    priceMAD: { min: 60, max: 120 },
    openingHours: '12:00 PM - 4:00 PM (Mon-Sat)',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
    tags: ['social-enterprise', 'local', 'authentic', 'budget-friendly'],
    isEcoCertified: true,
    isAccessible: true,
    hasShadedAreas: true,
    isFamilyFriendly: true,
  },
  {
    id: '17',
    name: 'Ensemble Artisanal',
    nameAr: 'مجمع الصناعة التقليدية',
    category: 'shopping',
    description: 'Government-run fixed-price artisan complex - perfect for learning fair prices before souk shopping.',
    address: 'Avenue Mohammed V, near Koutoubia',
    coordinates: [31.6228, -7.9968],
    rating: 4.1,
    reviews: 2134,
    priceRange: 2,
    priceMAD: { min: 0, max: 5000 },
    openingHours: '9:00 AM - 7:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=800',
    tags: ['shopping', 'fixed-price', 'crafts', 'authentic'],
    isAccessible: true,
    hasShadedAreas: true,
    isFamilyFriendly: true,
  },
  {
    id: '18',
    name: 'Palais Namaskar',
    nameAr: 'قصر نماسكار',
    category: 'hotel',
    description: 'Ultra-luxury resort with stunning water gardens and Moroccan-Asian fusion design.',
    address: 'Route de Bab Atlas, Km 12',
    coordinates: [31.5892, -8.0456],
    rating: 4.9,
    reviews: 1234,
    priceRange: 4,
    priceMAD: { min: 8000, max: 80000 },
    imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
    tags: ['ultra-luxury', 'spa', 'pool', 'tranquil'],
    isAccessible: true,
    hasShadedAreas: true,
    isFamilyFriendly: true,
  },
  {
    id: '19',
    name: 'Tanneries',
    nameAr: 'دباغة الجلود',
    category: 'monument',
    description: 'Traditional leather dyeing pits - a fascinating but intense sensory experience.',
    address: 'Bab Debbagh, Medina',
    coordinates: [31.6356, -7.9788],
    rating: 4.0,
    reviews: 4532,
    priceRange: 1,
    priceMAD: { min: 0, max: 50 },
    openingHours: '8:00 AM - 6:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1528657249085-893feaa06038?w=800',
    tags: ['cultural', 'leather', 'authentic', 'unique'],
    isAccessible: false,
    hasShadedAreas: false,
    isFamilyFriendly: false,
  },
  {
    id: '20',
    name: 'Ouzoud Waterfalls Day Trip',
    nameAr: 'شلالات أوزود',
    category: 'excursion',
    description: 'Spectacular 110m waterfalls with Barbary macaques, 2.5 hours from Marrakech.',
    ecoDescription: 'Natural wonder supporting local Berber communities.',
    address: 'Ouzoud (150km from Marrakech)',
    coordinates: [32.0156, -6.7167],
    rating: 4.6,
    reviews: 5678,
    priceRange: 2,
    priceMAD: { min: 300, max: 600 },
    openingHours: 'Full day excursion',
    imageUrl: 'https://images.unsplash.com/photo-1596627116790-af6f46dddbfe?w=800',
    tags: ['nature', 'waterfall', 'hiking', 'day-trip'],
    isEcoCertified: true,
    isAccessible: false,
    hasShadedAreas: true,
    isFamilyFriendly: true,
  },
]
